lib/mirage/factories/team.ts, package-lock.json, package.json, src/components/Team/CardList/Card/card.tsx
This PR adds a workaround to solve the SkeletonText breaking our Overview page.
Related to: https://github.com/chakra-ui/chakra-ui/issues/2956
=> Bugfix: SkeletonText was breaking Flex grid in Overview page

src/components/KeyResult/CheckInForm/Fields/CurrentConfidence/current-confidence.tsx, src/state/recoil/key-result/selectors/confidence-tag.spec.ts, src/state/recoil/key-result/selectors/confidence-tag.ts
This PR updates the threshold values for our confidence tag.
New values are:
* **HIGH**: from `67` to `100`
* **MEDIUM**: from `33` to `66`
* **LOW**: from `0` to `32`
=> Feature: Confidence Tag - Updates Thresholds Values

src/components/KeyResult/Single/Sections/Timeline/Cards/CheckIn/check-in.spec.tsx, src/components/KeyResult/Single/Sections/Timeline/Cards/CheckIn/check-in.tsx, src/components/KeyResult/Single/Sections/Timeline/Cards/CheckIn/progress.tsx
This PR fixes some null check-ins that were bugging our platform.
=> Hotfix: Null check-ins

src/components/KeyResult/CheckInForm/queries.gql, src/components/KeyResult/Single/Sections/Timeline/Cards/CheckIn/check-in.spec.tsx, src/components/KeyResult/Single/Sections/Timeline/Cards/CheckIn/check-in.tsx, src/components/KeyResult/Single/Sections/Timeline/Content/content.tsx, src/components/KeyResult/Single/Sections/Timeline/Content/entry.tsx
This PR fixes the broken mask in the value increase section of our Key Result timeline.
=> Bugfix: Timeline check-in value increase mask

src/components/Page/Team/ChildTeams/messages.ts, src/components/Page/Team/ChildTeams/team-list-searchable.tsx, src/components/Page/Team/ChildTeams/wrapper.tsx
Adds a search box for subteams, on Team page.
=> Feat: subteams search box

src/components/KeyResult/Single/Sections/Timeline/Cards/Comment/comment.tsx
Fixes a bug then mentioning users in comments with `-` character.
I've checked both regex using [regexr](https://regexr.com/6ajht), with those strings:
```
@[Gilbert Caillet-Bois](bdcb9199-ce5f-48b6-b50a-851e86795055)
@[Gilbert Caillet Bois](bdcb9199-ce5f-48b6-b50a-851e86795055)
@[Victor Perin](bdcb9199-ce5f-48b6-b50a-851e86795055)
@[Víctor Perin](bdcb9199-ce5f-48b6-b50a-851e86795055)
@[Victõr Perin](bdcb9199-ce5f-48b6-b50a-851e86795055)
@[Victôr Perin](bdcb9199-ce5f-48b6-b50a-851e86795055)
@[Victòr Perin](bdcb9199-ce5f-48b6-b50a-851e86795055)
@[Victör Perin](bdcb9199-ce5f-48b6-b50a-851e86795055)
@[Victör-Perin](bdcb9199-ce5f-48b6-b50a-851e86795055)
```
* https://github.com/budproj/business/pull/155
=> bugfix(components/comment): allow char '-' as part of a name

manifests/canary/canary-deployment.yaml
This PR works together with auth0 new configuration to allow logins from domain `auth.getbud.co`.
- https://auth0.com/docs/brand-and-customize/custom-domains/auth0-managed-certificates
=> Feat: auth subdomain

manifests/stable/deployment.yaml
This PR works together with auth0 new configuration to allow logins from domain `auth.getbud.co`.
- https://auth0.com/docs/brand-and-customize/custom-domains/auth0-managed-certificates
=> Feat: auth subdomain stable

src/components/Page/Team/Members/members.tsx
Disable user's card on the teams' page
Go to the Teams page and hover over a user name, the card should not be loaded.
=> Disable users card on team page

src/components/Team/Select/queries.gql
In explore team page, we do not get all teams listed in the root team.
A temporary solution is only change the limit of teams to get from graphql. (by default is 20)
A more robust solution is needed. Fixing pagination in the backend and modify the components to fetch each page when needed is the correct solution to aim for.
=> bugfix(team/select): not listing all teams

src/components/Team/Select/styled-wrapper.tsx, src/components/Team/Select/wrapper.tsx, src/components/User/Teams/add-team.tsx
Prevent team list to overflow the drawer creating a new hasScroll flag.
Open the team list on the user options and it should have a scroll.
=> Add scroll option to team list

src/components/KeyResult/Single/Sections/Checklist/ActionButtons/change-assigned.tsx
Restore the previous behavior for arrows icon when the task owner editing is hovered
=> Keep task state as editing when popover is opened

src/components/KeyResult/Single/Sections/Checklist/queries.gql
Resolves a problem with some clients creating checkmarks but not able to see them.
=> bugfix(components/kr/checklist): list first 1000 checkmarks instead of 20, by default

src/components/User/Me/me.tsx, src/components/User/Me/queries.gql, src/state/hooks/useAmplitude/marshal-amplitude-user.ts, src/state/hooks/useAmplitude/types.ts
Allow Amplitude to know if a user is a team leader.
Added the flag isTeamLeader in the query to get this information from the backend.
Use this extension: [`Amplitude Event Explorer`](https://chrome.google.com/webstore/detail/amplitude-event-explorer/acehfjhnmhbmgkedjmjlobpgdicnhkbp), and verify if the isTeamLeader tag is passed.
- [`BUD22-421`](https://getbud.atlassian.net/jira/software/projects/BUD22/boards/16?assignee=622f47431c09d2007012fa64&selectedIssue=BUD22-421)
- [`business#203`](https://github.com/budproj/business/pull/203)
=> feat(amplitude/track-teamleader) track isTeamLeader flag on Amplitude

src/components/Team/SaveTeamModal/save-team-modal.tsx
Fix the owner selector when on the create team modal
Set the current user as default owner when the modal is creation
Click on the create menu button and it should show the current user as owner
=> fix(team/create): set current user as owner of a new team

src/components/Cycle/List/Body/Columns/DateEnd/date-end.tsx, src/components/Cycle/List/Body/Columns/DateStart/date-start.tsx
The dates for cycles on the listing table are presented as the day before
It considers the dates as UTC when displaying.
Go to the cycle page and the date on the table should be the same as the date on the modal.
- [`BUD22-479`](https://getbud.atlassian.net/browse/BUD22-479)
=> fix(cycle-date): parse date as utc timezone

lang/en-US.json, lang/pt-BR.json, src/components/Base/MenuOptions/index.tsx, src/components/Base/MenuOptions/messages.ts, src/components/Notifications/Modal/index.tsx, src/components/Page/Team/Tabs/content/messages.ts, src/components/Routine/RetrospectiveTab/Answers/AnswerContent/AnswerCards/HistoryAnswersCard/history-answers.tsx, src/components/Routine/RetrospectiveTab/Answers/AnswerContent/AnswerCards/HistoryAnswersCard/messages.ts, src/components/Routine/RetrospectiveTab/Answers/AnswerContent/index.tsx, src/components/Routine/RetrospectiveTab/Answers/answer-row.tsx, src/components/Routine/RetrospectiveTab/Answers/index.tsx, src/components/Routine/RetrospectiveTab/Answers/messages.ts, src/components/Routine/RetrospectiveTab/RoutinesOverview/index.tsx, src/components/Routine/RetrospectiveTab/retrospective-tab-content.tsx, src/components/Routine/hooks/deleteAnswer/delete-routine-answer.tsx, src/components/Routine/hooks/deleteAnswer/messages.ts, src/components/Routine/hooks/getPendingRoutine/get-pending-routines.tsx, src/components/Routine/hooks/setComment/set-comment.tsx, src/components/Routine/hooks/setRoutineFormAnswers/set-routine-form-answers.tsx, src/state/recoil/routine/answer-summary.ts, src/state/recoil/routine/overview-data.ts
Allow a user to delete their response from routines.
* Implementation of an action menu where the user selects the button to delete the routine.
* The button should only appear if the user owns the answer.
* When deleting a response, the routine data is updated, and the user can respond again.
[A brief description of how the reviewer can test my PR.](https://drive.google.com/file/d/1N6SgtAVw7W0zh4cfIKoOVmrZLWNQ1J07/view?usp=share_link)
- [`BUD22-464`](https://getbud.atlassian.net/jira/software/projects/BUD22/boards/16?selectedIssue=BUD22-464)
- [`routines-microservice#93`](https://github.com/budproj/routines-microservice/pull/93)
=> feat(routin/delete)

src/components/Base/NoticesBanner/index.tsx, src/components/Routine/RetrospectiveTab/Comments/CommentCard/index.tsx, src/components/Routine/RetrospectiveTab/Comments/CommentInput/custom-mentions-input.tsx, src/state/hooks/useEvent/event-type.ts, src/state/hooks/useEvent/event.ts, src/state/hooks/useEvent/events/learn-more-banner-notices-click-data.ts
- Creating a news banner to notify a Retrospective feature.
- Foi implementado um componente que é renderizado acima dos conteúdos das páginas, em _app. 
- O banner é setado como false no localstorage quando o usuário o fecha.
- [`BUD22-EDP38`](https://getbud.atlassian.net/browse/EPD-38)
=> feat(notices/banner)

src/components/Workspace/CreateForm/wrapper.tsx, src/state/recoil/routine/post-create-team-settings.ts
Ao criar um novo time, as configurações de rotinas não eram criadas.
Ao preencher o formulario de novo workspace, fazer um request para o microserviço de rotinas.
Navegar para `/new-workspace` e preencher o formulario. O request para o microserviço de rotinas deve ser um sucesso. Verificar se o registro no banco do microserviço é criado e se a mensagem do nats para o microserviço de scheduling é enviada.
- [`EPD-48`](https://getbud.atlassian.net/browse/EPD-48)
- budproj/routines-microservice#102
=> [EPD-48] feat(components/Workspace/CreateForm): create routines settings

src/components/KeyResult/Single/Drawer/Body/body.tsx, src/components/KeyResult/Single/Sections/Timeline/timeline.tsx
Comentários não carregam em link para KR
Comments (timeline) were loading before key result.
**Quando sou marcado em um KR que não sou responsável nem apoio, sou direcionado para o link abaixo que me leva agora para a página do time, porém a sidebar do KR não carrega o conteúdo (comenatários e check-ins):**
https://app.getbud.co/explore/f717b12f-2cc0-45c7-8f35-2b3f4ae5e65c?keyResultId=0ee2bc3f-2aa3-44d2-9974-f521ac28c0cc&utm_source=bud&utm_medium=email&utm_campaign=notification&utm_content=mention
=> Fix: comments loading before keyresult.

src/components/Base/KeyResultListing/index.tsx, src/components/KeyResult/Single/Drawer/drawer.tsx, src/state/recoil/key-result/key-result-list.ts
When you open Key Result from confidence list, the Key result modal had mouse interactions not working property.
It was needed to close modal of confidence key result list before open key result modal, opening those at same time create component focus conflict.
1. Open bud
2. Select one confidence level from dashboard
3. Select one Key result from the list
4. Try to up and down the page using mouse scroll
- [`BUD22-123`](https://www.notion.so/budops/Bug-scroll-ao-abrir-um-kr-pelo-painel-eec593b2653d488f9ad154dd4723f984?pvs=4)
=> fix: mouse events from key result drawer not working

src/components/Page/Dashboard/dashboard.tsx, src/components/Report/BoardsOverview/KeyResultConfidences/index.tsx
Resolver bug que impedia o usuário de editar KR no painel.
Incluir o componente de edição no dashboard. 
Criar um reset de estado para o modal de lista de KR.
1. No painel, selecionar um nível de confiança com KR.
2. Selecionar um KR.
3. Editar o KR.
4. Verificar resultado e comportamento dos modais.
https://www.notion.so/budops/Bug-ao-tentar-editar-KR-atrav-s-do-Painel-8827b28dda234c0e91194ce9902f0195?pvs=4
=> Bug ao tentar editar KR através do Painel

src/components/Page/Team/Tabs/content/board-tab-content.tsx
Need to remove a suggestion button in task tab content
Remove the functionality and the button display
Tested in localhost
- [`BUD22-123`](https://www.notion.so/budops/28fc5005cf3340f68de1468b2fd83b37?v=c01d6b713e204f1f97f8ed3a2a11b464&p=5059183520164f52b3d1c06945eb5e6d&pm=s)
=> fix:Removed suggestion button and the functionallity

src/components/Team/CardList/queries.gql
Lista de “Membros do Time” está repetindo o último nome da lista sempre que um user faz o seguinte caminho:
1. Acessar a página de um time;
2. Passar o cursor do mouse pelo botão `Times` (no menu superior do Bud)
Query was missing some parameters
1. Acessar a página de um time;
2. Passar o cursor do mouse pelo botão `Times` (no menu superior do Bud)
=> Fix: repeated tem members on list.

src/components/Base/MentionField/index.tsx, src/components/Base/MentionField/queries/queries.gql, src/components/Base/MentionField/utils/messages.ts, src/components/Base/MentionField/utils/render-suggestion.tsx, src/components/Base/MentionField/utils/types.ts, src/components/KeyResult/CheckInForm/Fields/Comment/input.tsx, src/components/KeyResult/CheckInForm/form.tsx, src/components/KeyResult/Single/Sections/Timeline/Cards/CheckIn/comment.tsx
Implements the feature that allows the user to mark another in check-in comments.
1 - Go to app
2 - Go to KR
3 - Make a check-in
4 - Comment the check-in
5 - Mark user
6 - Check email to see if you where marked
- [`BUD22-123`](https://www.notion.so/budops/Melhoria-Como-KR-Owner-gostaria-de-fazer-um-check-in-e-marcar-pessoas-que-preciso-na-mesma-a-o-b5c4a5601d8d4dd59e2887c7a8063ead?pvs=4)
=> implements feature, users can be marked on check in comments
