budproj/execution-mode

- .gitattributes
- .gitignore
> Chores: Yarn

- src/next.config.js
> Bugfix: INTL links

- manifests/develop/deployment.yaml
- src/pages/_app.tsx
- src/state/recoil/authz/selectors.spec.ts
- src/state/recoil/authz/selectors.ts
- src/state/recoil/authz/types.ts
This PR refactors our Authz integration to use correct tenants.
> Refactor: Authz Tenants

- .env.example
- lib/apollo/index.ts
- manifests/develop/deployment.yaml
This PR fixes some errors in our back-end integration.
> Bugfix: Back-end integration

- jest.config.js
- lib/mirage/schema.gql
- package-lock.json
- src/components/Base/AppBar/app-bar.tsx
- src/components/Base/RecoilDebugObserver/recoil-debug-observer.tsx
- src/components/KeyResult/ProgressSlider/slider.spec.tsx
- src/components/KeyResult/ProgressSlider/slider.tsx
- src/components/KeyResult/Single/Title/title.spec.tsx
- src/components/KeyResult/Single/Title/title.tsx
- src/components/KeyResult/View/Body/draggable-grid.tsx
- src/components/User/Me/index.ts
- src/components/User/Me/me.spec.tsx
- src/components/User/Me/me.tsx
- src/components/User/NamedAvatar/named-avatar.tsx
- src/components/User/index.ts
- src/components/User/queries.gql
- src/global.d.ts
- tsconfig.json
- tsconfig.server.json
- tsconfig.test.json
This PR fixes bugs found in our first usability test.
> Bugfix: V1 Usability Tests

- src/components/Objective/AccordionItem/accordion-button.tsx
- src/components/Team/ChildTeamsObjectives/child-teams-objectives.spec.tsx
- src/components/Team/ChildTeamsObjectives/child-teams-objectives.tsx
This PR fixes some bugs to deploy our team structure feature.
> Bugfix: Team structure deploy

- src/components/KeyResult/CheckInForm/form.spec.tsx
- src/components/KeyResult/CheckInForm/form.tsx
- src/components/KeyResult/Single/Drawer/drawer.tsx
This PR fixes the bug that was preventing our users from creating check-ins in our key result drawer.
> Bugfix: Drawer Check-in

- lang/pt-BR.json
- src/components/KeyResult/CheckInForm/actions.spec.tsx
- src/components/KeyResult/CheckInForm/actions.tsx
- src/components/KeyResult/CheckInForm/form.spec.tsx
- src/components/KeyResult/CheckInForm/form.tsx
- src/components/KeyResult/CheckInForm/messages.ts
- src/components/KeyResult/ProgressSlider/popover.spec.tsx
- src/components/KeyResult/ProgressSlider/popover.tsx
- src/components/KeyResult/ProgressSlider/wrapper.spec.tsx
- src/components/KeyResult/ProgressSlider/wrapper.tsx
- src/themes/preset-base/components/button.ts
This PR adds a cancel button to our check-in form.
> Feature: Check-in cancel button

- src/components/Base/SelectMenu/select-menu.tsx
Fixes the ghost menu options on check-in form
> Hotfix: Check-in Ghost Menu Options

- lang/pt-BR.json
- lib/mirage/factories/cycle.ts
- lib/mirage/schema.gql
- src/components/Cycle/types.ts
- src/components/KeyResult/List/Body/Columns/Cycle/cycle.tsx
- src/components/KeyResult/Single/Drawer/queries.gql
- src/components/KeyResult/Single/Sections/Cycle/cycle.tsx
- src/components/KeyResult/Single/Sections/Cycle/date-with-title.spec.tsx
- src/components/KeyResult/Single/Sections/Cycle/date-with-title.tsx
- src/components/KeyResult/Single/Sections/Cycle/messages.ts
- src/components/KeyResult/View/queries.gql
- src/components/Objective/AccordionItem/queries.gql
This PR integrates with the new backend to show the Cycle name
> Feature: Cycle Name

- src/components/Base/Breadcrumb/breadcrumb.spec.tsx
- src/components/Base/Breadcrumb/breadcrumb.tsx
This PR removes the default Home item from the breadcrumb.
> Feature: Removes Home from Breadcrumb

- lang/pt-BR.json
- src/components/KeyResult/CheckInForm/Fields/CurrentConfidence/current-confidence.tsx
- src/state/recoil/key-result/selectors/confidence-tag.spec.ts
- src/state/recoil/key-result/selectors/confidence-tag.ts
- src/state/recoil/key-result/selectors/messages.ts
This PR adds the barrier tag to our confidence tag component.
> Feature: Confidence Tag - Adds Barrier tag

- lib/mirage/seeds/index.ts
- package-lock.json
- package.json
- src/components/Base/SliderWithGoal/slider-with-goal.spec.tsx
- src/components/Base/SliderWithGoal/slider-with-goal.tsx
- src/components/KeyResult/CheckInForm/Fields/Goal/goal.tsx
- src/components/Team/CardList/Card/card.tsx
- src/state/recoil/key-result/selectors/current-progress.spec.ts
- src/state/recoil/key-result/selectors/current-progress.ts
This PR fixes some minor bugs reported in our V0 tests.
> Bugfix: V0 minor bugs

- src/state/recoil/key-result/selectors/current-progress.spec.ts
- src/state/recoil/key-result/selectors/current-progress.ts
- src/state/recoil/types.ts
This PR adds the Current Progress Setter that I've forgot to add in #43
> Hotfix: Current Progress Setter

- lib/mirage/factories/user.ts
- lib/mirage/schema.gql
- src/components/Base/DynamicAvatarGroup/dynamic-avatar-group.tsx
- src/components/Base/DynamicAvatarGroup/dynamic-group.spec.tsx
- src/components/KeyResult/List/Body/Columns/ConfidenceLevel/confidence-level.tsx
- src/components/KeyResult/List/Body/Columns/Owner/owner.tsx
- src/components/KeyResult/Single/Drawer/queries.gql
- src/components/KeyResult/Single/Sections/Owner/owner.tsx
- src/components/KeyResult/View/queries.gql
- src/components/Objective/AccordionItem/queries.gql
- src/components/Page/Dashboard/dashboard.spec.tsx
- src/components/Page/Dashboard/dashboard.tsx
- src/components/Page/Dashboard/queries.gql
- src/components/Report/CompanyProgressOverview/Body/Stamps/Company/company.spec.tsx
- src/components/Report/CompanyProgressOverview/Body/Stamps/Company/company.tsx
- src/components/Report/CompanyProgressOverview/queries.gql
- src/components/Team/CardList/queries.gql
- src/components/User/Me/me.spec.tsx
- src/components/User/Me/me.tsx
- src/components/User/Me/queries.gql
- src/components/User/NamedAvatar/named-avatar.tsx
- src/components/User/types.ts
- src/state/recoil/key-result/selectors/build-partial-selector.spec.ts
- src/state/recoil/key-result/selectors/key-result.spec.ts
- src/state/recoil/key-result/selectors/latest-confidence-report.spec.ts
> Feature: Split user name

- lang/pt-BR.json
- package-lock.json
- package.json
- src/components/Base/AppBar/app-bar.tsx
- src/components/User/Logout/index.ts
- src/components/User/Logout/logout.spec.tsx
- src/components/User/Logout/logout.tsx
- src/components/User/Logout/messages.ts
- src/components/User/Me/me.tsx
- src/components/User/NamedAvatar/named-avatar.tsx
- src/pages/_app.tsx
- src/themes/preset-base/components/button.ts
- src/themes/preset-base/components/index.ts
- src/themes/preset-base/components/menu.ts
- src/themes/preset-base/theme.ts
This PR adds the logout button to our AppBar
> Feature: Logout button

- src/components/KeyResult/DynamicIcon/dynamic-icon.spec.tsx
- src/components/KeyResult/List/Head/head.spec.tsx
- src/components/KeyResult/List/list.tsx
- src/components/KeyResult/View/view.spec.tsx
- src/components/KeyResult/View/view.tsx
This PR adds some missing unit tests. It aims to solve partially #22
> Chore: Adds some missing unit tests

- package-lock.json
- src/components/KeyResult/CheckInForm/actions.tsx
- src/components/KeyResult/List/Body/Columns/Owner/owner.tsx
- src/components/KeyResult/ProgressSlider/popover.spec.tsx
- src/components/KeyResult/ProgressSlider/popover.tsx
This PR fixes some issues while clicking in our Key Result list.
> Bugfix: Key Result List click

- lang/pt-BR.json
- src/components/KeyResult/List/Head/messages.ts
- src/components/Report/ObjectivesOverview/Header/header.spec.tsx
- src/components/Report/ObjectivesOverview/Header/header.tsx
- src/components/Report/ObjectivesOverview/Header/messages.ts
- src/components/Report/ObjectivesOverview/objectives-overview.tsx
- src/components/Report/ObjectivesOverview/queries.gql
This PR updates some of our texts.
> Refactor: Changes the text in some components

- lang/en-US.json
- lang/pt-BR.json
- src/components/KeyResult/CheckInForm/Fields/Comment/input.spec.tsx
- src/components/KeyResult/CheckInForm/Fields/Comment/input.tsx
- src/components/KeyResult/CheckInForm/Fields/Comment/messages.ts
- src/components/KeyResult/CheckInForm/form.spec.tsx
- src/components/KeyResult/CheckInForm/form.tsx
- src/components/KeyResult/Single/Sections/CheckIn/check-in.tsx
- src/state/recoil/key-result/selectors/index.ts
- src/state/recoil/key-result/selectors/latest-confidence-report.spec.ts
- src/state/recoil/key-result/selectors/latest-confidence-report.ts
- src/state/recoil/key-result/selectors/latest-report.spec.ts
- src/state/recoil/key-result/selectors/latest-report.ts
This PR adds the button to save comments on the drawer.
> Bugfix: Go Live - Add button to save comments on drawer

- src/components/KeyResult/CheckInForm/Fields/Comment/comment.tsx
- src/components/KeyResult/CheckInForm/actions.spec.tsx
- src/components/KeyResult/CheckInForm/actions.tsx
- src/components/KeyResult/CheckInForm/form.spec.tsx
- src/components/KeyResult/CheckInForm/form.tsx
- src/components/KeyResult/ProgressSlider/popover.tsx
- src/components/KeyResult/Single/Drawer/drawer.spec.tsx
- src/components/KeyResult/Single/Drawer/drawer.tsx
- src/components/KeyResult/Single/Sections/CheckIn/check-in.tsx
This PR allows the user to add check-in only with comments too.
> Refactor: Only comment check-ins

- lang/pt-BR.json
- src/components/KeyResult/List/list.tsx
- src/components/KeyResult/View/view.spec.tsx
- src/components/KeyResult/View/view.tsx
- src/components/Objective/AccordionItem/accordion-panel.spec.tsx
- src/components/Objective/AccordionItem/accordion-panel.tsx
This PR fixes the flickering that was happening on the key result list empty state.
> Bugfix: Key Result List empty state

- lang/pt-BR.json
- src/components/KeyResult/List/list.tsx
- src/components/KeyResult/View/view.spec.tsx
- src/components/KeyResult/View/view.tsx
- src/components/Objective/AccordionItem/accordion-panel.spec.tsx
- src/components/Objective/AccordionItem/accordion-panel.tsx
This follows up previous PR #59
> Bugfix: Key Result List

- src/components/KeyResult/Single/Drawer/Body/body.spec.tsx
- src/components/KeyResult/Single/Drawer/Body/body.tsx
- src/components/Objective/AccordionItem/accordion-panel.tsx
- src/components/Page/Explore/Team/team.tsx
This PR adds the Key Result Drawer to our Team Objectives page.
> Feature: Key Result Drawer in Team Objectives Page

- lib/mirage/graphql-handler.ts
- src/components/KeyResult/Single/Drawer/Header/header.spec.tsx
- src/components/KeyResult/Single/Drawer/Header/header.tsx
- src/components/KeyResult/types.ts
> Bugfix: Timeline

- src/components/KeyResult/CustomList/custom-list.tsx
This PR fixes the custom list that was overwritting the state.
> Bugfix: Fixes custom list overwritting state

- src/components/KeyResult/CustomList/custom-list.tsx
> Bugfix: Custom list

- src/components/KeyResult/ProgressSlider/wrapper.spec.tsx
- src/components/KeyResult/ProgressSlider/wrapper.tsx
- src/components/KeyResult/Single/Drawer/drawer.spec.tsx
- src/components/KeyResult/Single/Drawer/drawer.tsx
- src/components/KeyResult/Single/Sections/CheckIn/check-in.spec.tsx
- src/components/KeyResult/Single/Sections/CheckIn/check-in.tsx
This PR fixes the close check-in bug
> Bugfix: Close check-in

- lib/mirage/graphql-handler.ts
- src/components/Base/Breadcrumb/breadcrumb.spec.tsx
- src/components/Base/Breadcrumb/breadcrumb.tsx
- src/components/KeyResult/CheckInForm/Fields/NewProgress/new-progress.spec.tsx
- src/components/KeyResult/CheckInForm/Fields/NewProgress/new-progress.tsx
- src/components/KeyResult/CheckInForm/form.spec.tsx
- src/components/KeyResult/CheckInForm/form.tsx
- src/components/KeyResult/ProgressSlider/slider.spec.tsx
- src/components/KeyResult/ProgressSlider/slider.tsx
- src/components/KeyResult/Single/Drawer/Header/header.tsx
- src/components/KeyResult/Single/Drawer/content.tsx
- src/components/KeyResult/Single/Drawer/drawer.spec.tsx
- src/components/KeyResult/Single/Drawer/drawer.tsx
- src/components/KeyResult/Single/Sections/Timeline/Cards/CheckIn/relative-confidence-tag.spec.tsx
- src/components/KeyResult/Single/Sections/Timeline/Cards/CheckIn/relative-confidence-tag.tsx
- src/components/KeyResult/Single/Sections/Timeline/timeline.tsx
- src/components/Objective/AccordionItem/accordion-button.tsx
This PR fixes some issues created by our canary release of the timeline comment feature.
> Bugfix: Timeline canary release

- lang/pt-BR.json
- src/components/Base/SliderWithFilledTrack/slider-with-filled-track.spec.tsx
- src/components/Base/SliderWithFilledTrack/slider-with-filled-track.tsx
- src/components/KeyResult/Single/Sections/Timeline/Cards/Base/base.tsx
- src/components/KeyResult/Single/Sections/Timeline/Cards/CheckIn/comment.tsx
- src/components/KeyResult/Single/Sections/Timeline/Cards/CheckIn/messages.ts
- src/components/KeyResult/Single/Sections/Timeline/Cards/CheckIn/progress-bar.tsx
This PR adds the new comment structure in the timeline.
> Feature: New comment structure in timeline

- src/components/Base/PercentageProgressIncreaseTag/percentage-progress-increase-tag.spec.tsx
- src/components/Base/PercentageProgressIncreaseTag/percentage-progress-increase-tag.tsx
- src/components/KeyResult/Single/Sections/Timeline/timeline.tsx
- src/components/Report/TeamsOverview/teams-overview.spec.tsx
This PR fixes some dashboard issues and Apollo queries.
> Bugfix: Fixes some dashboard issues

- src/components/KeyResult/types.ts
- src/components/Objective/AccordionItem/accordion-button.spec.tsx
- src/components/Objective/AccordionItem/accordion-button.tsx
- src/components/Objective/AccordionItem/accordion-item.spec.tsx
- src/components/Objective/AccordionItem/accordion-item.tsx
- src/components/Objective/types.ts
- src/components/Report/CompanyProgressOverview/Body/body.spec.tsx
- src/components/Report/CompanyProgressOverview/Body/body.tsx
- src/components/Report/CompanyProgressOverview/queries.gql
- src/components/Report/ObjectivesOverview/Body/Line/line.spec.tsx
- src/components/Report/ObjectivesOverview/Body/Line/line.tsx
- src/components/Report/ObjectivesOverview/queries.gql
- src/components/Report/TeamsOverview/Body/Table/Body/Columns/Progress/progress.spec.tsx
- src/components/Report/TeamsOverview/Body/Table/Body/Columns/Progress/progress.tsx
- src/components/Report/TeamsOverview/queries.gql
- src/components/Report/TeamsOverview/teams-overview.spec.tsx
- src/components/Team/CardList/Card/card.spec.tsx
- src/components/Team/CardList/Card/card.tsx
- src/components/Team/CardList/queries.gql
- src/components/Team/ChildTeamsObjectives/queries.gql
- src/components/Team/types.ts
This PR integrates with the new cycle filtered back-end.
> Feature: Integrates with new cycle filtered back-end

- src/components/Base/ExpandableText/expandable-text.tsx
- src/themes/preset-base/theme.ts
- src/themes/tokens.ts
This PR updates our theme color tokens to the new color scheme.
> Feature: Update theme color tokens

- lib/mirage/factories/index.ts
- lib/mirage/factories/objective.ts
- lib/mirage/factories/status.ts
- lib/mirage/factories/team.ts
- lib/mirage/graphql-handler.ts
- lib/mirage/models.ts
- lib/mirage/schema.gql
- lib/mirage/seeds/index.ts
This PR updates the MirageJS schema, by adding the new status structure.
> Chore: Updates MirageJS schema

- lang/pt-BR.json
- lib/mirage/schema.gql
- lib/mirage/seeds/index.ts
- src/components/KeyResult/NumberMasks/Base/base.tsx
- src/components/KeyResult/Single/Sections/Timeline/Cards/CheckIn/check-in.spec.tsx
- src/components/KeyResult/Single/Sections/Timeline/Cards/CheckIn/check-in.tsx
- src/components/KeyResult/Single/Sections/Timeline/Cards/CheckIn/comment.tsx
- src/components/KeyResult/Single/Sections/Timeline/Cards/CheckIn/constants.ts
- src/components/KeyResult/Single/Sections/Timeline/Cards/CheckIn/messages.ts
- src/components/KeyResult/Single/Sections/Timeline/Cards/CheckIn/value-increase.spec.tsx
- src/components/KeyResult/Single/Sections/Timeline/Cards/CheckIn/value-increase.tsx
- src/components/KeyResult/Single/Sections/Timeline/queries.gql
- src/components/KeyResult/types.ts
- src/components/Report/CompanyProgressOverview/Body/Stamps/ProgressIncrease/constants.ts
- src/components/Report/CompanyProgressOverview/Body/Stamps/ProgressIncrease/progress-increase.tsx
- src/components/Report/CompanyProgressOverview/Header/header.spec.tsx
- src/state/hooks/useValueSignal/constants.ts
- src/state/hooks/useValueSignal/hook.spec.tsx
- src/state/hooks/useValueSignal/hook.ts
- src/state/hooks/useValueSignal/index.ts
- src/themes/tokens.ts
This PR creates the value increase section in the timeline.
> Feature: Check-in card value increase section

- src/components/Base/Breadcrumb/breadcrumb.tsx
- src/components/Base/SliderWithDetails/slider-with-details.tsx
- src/components/Base/SliderWithFilledTrack/slider-with-filled-track.tsx
- src/components/KeyResult/ConfidenceTag/confidence-tag.tsx
- src/components/KeyResult/Single/Sections/AddCheckIn/add-check-in.tsx
- src/themes/preset-base/components/button.ts
This PR fixes some color issues
> Bugfix: Minor color adjustments

- lib/mirage/factories/user.ts
- src/components/Base/EditableSelectField/editable-select-field.tsx
This PR fixes the color of the gender setttings.
> Bugfix: Settings gender

- .eslintrc
- lang/pt-BR.json
- src/components/Base/SettingsButton/messages.ts
- src/components/Base/SettingsButton/settings-button.tsx
- src/components/Base/SliderWithHoverThumb/slider-with-hover-thumb.spec.tsx
- src/components/Base/SliderWithHoverThumb/slider-with-hover-thumb.tsx
- src/components/Base/SupportButton/messages.ts
- src/components/Base/SupportButton/support-button.tsx
- src/components/KeyResult/CheckInForm/Fields/Confidence/confidence.tsx
- src/components/KeyResult/CheckInForm/Fields/Confidence/messages.ts
- src/components/KeyResult/List/Body/Columns/Progress/messages.ts
- src/components/KeyResult/List/Body/Columns/Progress/progress.spec.tsx
- src/components/KeyResult/List/Body/Columns/Progress/progress.tsx
- src/components/KeyResult/List/Head/head.tsx
- src/components/KeyResult/List/Head/messages.ts
- src/components/KeyResult/ProgressSlider/messages.ts
- src/components/KeyResult/ProgressSlider/slider.tsx
- src/components/Objective/AccordionItem/accordion-button.tsx
- src/components/Objective/AccordionItem/messages.ts
- src/components/Report/TeamsOverview/Body/Table/Head/head.tsx
- src/components/Report/TeamsOverview/Body/Table/Head/messages.ts
- src/themes/preset-base/components/tooltip.ts
This PR adds the simple tooltips to our platform.
> Feature: Simple tooltips

- lang/pt-BR.json
- src/components/Icon/LinkedIn/index.ts
- src/components/Icon/LinkedIn/linked-in.spec.tsx
- src/components/Icon/LinkedIn/linked-in.tsx
- src/components/Icon/index.ts
- src/components/KeyResult/CustomList/queries.gql
- src/components/KeyResult/List/Body/Columns/Owner/owner.tsx
- src/components/Objective/AccordionItem/queries.gql
- src/components/Settings/Account/Body/body.tsx
- src/components/Settings/Account/UserCardPreview/index.ts
- src/components/Settings/Account/UserCardPreview/messages.ts
- src/components/Settings/Account/UserCardPreview/user-card-preview.tsx
- src/components/Settings/Account/account.tsx
- src/components/User/Avatar/avatar.tsx
- src/components/User/ProfileCard/index.ts
- src/components/User/ProfileCard/messages.ts
- src/components/User/ProfileCard/profile-card.tsx
- src/components/User/TeamTags/team-tags.tsx
- src/themes/preset-base/components/popover.ts
This PR updates the user card and adds the preview column to the account settings page.
> Feature: Settings Preview User Card

- src/components/Base/AppBar/UserMenu/user-menu.tsx
This PR fixes the actionable area of the User Menu items.
> Bugfix: User Menu

- src/components/Base/EditableInputValue/editable-input-value.spec.tsx
- src/components/Base/EditableSelectValue/editable-select-value.spec.tsx
- src/components/Base/EditableTextAreaValue/editable-text-area-value.spec.tsx
- src/components/KeyResult/ConfidenceTag/confidence-tag.spec.tsx
- src/components/KeyResult/DynamicIcon/dynamic-icon.spec.tsx
- src/components/KeyResult/Single/Sections/Timeline/Cards/CheckIn/progress.spec.tsx
- src/components/Objective/AccordionItem/accordion-item.spec.tsx
- src/components/Report/CompanyProgressOverview/Body/Stamps/ProgressIncrease/progress-increase.spec.tsx
- src/components/Settings/Account/Body/PersonalInformations/personal-informations.spec.tsx
- src/components/Settings/Account/Body/PersonalInformations/personal-informations.tsx
- src/components/Settings/Account/Body/SocialMedia/social-media.spec.tsx
- src/components/Settings/Account/Body/SocialMedia/social-media.tsx
- src/components/Settings/Account/Header/header.spec.tsx
- src/components/User/Avatar/avatar.spec.tsx
- src/components/User/ProfileCard/profile-card.spec.tsx
- src/components/User/ProfileCard/profile-card.tsx
- src/components/User/TeamTags/team-tags.spec.tsx
- src/components/User/TeamTags/team-tags.tsx
- src/state/hooks/useConfidenceTag/hook.spec.tsx
Fixes bugs and finishes unit tests regarding our user card preview.
> Bugfix: User card preview

- src/components/KeyResult/OwnedByUser/owned-by-user.spec.tsx
- src/components/KeyResult/OwnedByUser/owned-by-user.tsx
This PR solves the empty query that we were doing upon fetching key results.
> Bugfix: Empty Key Result Query

- lang/pt-BR.json
- src/state/hooks/useCadence/hook.spec.tsx
- src/state/hooks/useCadence/hook.ts
- src/state/hooks/useCadence/messages.ts
This PR fixes the quarterly cadence prefix.
> Bugfix: Cadence Prefix

- src/components/Objective/AccordionItem/accordion-panel.tsx
- src/components/Objective/AccordionItem/queries.gql
This PR enables the last update text flag in the explore key result table.
> Feature: Adds last update text to explore

- .env.development
- .env.local.example
This PR improves how we handle env vars.
> Chore: Improves env vars

- package-lock.json
- package.json
- src/components/Base/ProgressBar/index.ts
- src/components/Base/ProgressBar/progress-bar.tsx
- src/components/Base/index.ts
- src/pages/_app.tsx
Adds a progress bar to show progress while changing routes.
> Feature: Progress bar

- .env.development
- lib/mirage/graphql-handler.ts
- src/components/Base/ButtonOptionGroup/button-option-group.spec.tsx
- src/components/Cycle/Filter/QuarterSelector/quarter-selector.spec.tsx
- src/components/Cycle/Filter/YearSelector/queries.gql
- src/components/Cycle/Filter/YearSelector/year-list.spec.tsx
- src/components/Cycle/Filter/YearSelector/year-selector.spec.tsx
- src/components/Cycle/Filter/YearSelector/year-selector.tsx
- src/components/KeyResult/ActiveAndOwnedByUser/active-and-owned-by-user.spec.tsx
- src/components/KeyResult/CycleList/cycle-list.spec.tsx
- src/components/KeyResult/NotActiveAndOwnedByUser/not-active-and-owned-by-user.spec.tsx
- src/components/KeyResult/NotActiveAndOwnedByUser/not-active-and-owned-by-user.tsx
- src/components/KeyResult/ProgressSlider/slider.spec.tsx
- src/components/KeyResult/Single/Drawer/Footer/footer.spec.tsx
- src/components/KeyResult/Single/Drawer/content.spec.tsx
- src/components/KeyResult/Single/Drawer/content.tsx
- src/components/Objective/AccordionItem/accordion-button.spec.tsx
- src/components/Page/Error/UnderMaintenance/under-maintenance.spec.tsx
- src/components/Page/MyKeyResults/PreviousCycles/previous-cycles.spec.tsx
- src/state/recoil/cycle/select-from-list.spec.ts
This PR adds the missing unit tests.
> Chore: Unit tests on Cadence at My Key Results

- manifests/stable/deployment.yaml
- src/components/KeyResult/Single/Drawer/Body/body.tsx
- src/components/KeyResult/Single/Sections/Description/description.tsx
> Bugfix: Lint

- lang/pt-BR.json
- src/components/KeyResult/Single/Sections/Timeline/Cards/EmptyState/messages.ts
> Intl: Update messages

- lang/pt-BR.json
- package-lock.json
- package.json
- scripts/postinstall.sh
- src/components/KeyResult/Single/Drawer/Body/body.tsx
- src/components/KeyResult/Single/Sections/Description/messages.ts
This PR fixes some bugs regarding the update feature in our key-result
> Bugfix: Key Result Update

- lang/pt-BR.json
- src/components/Base/EditableTextAreaValue/editable-text-area-value.tsx
- src/components/KeyResult/ActiveAndOwnedByUser/active-and-owned-by-user.tsx
- src/components/KeyResult/ActiveAndOwnedByUser/cycle-lists.tsx
- src/components/KeyResult/CycleList/cycle-list.tsx
- src/components/KeyResult/Single/Sections/Owner/Update/interface.ts
- src/components/KeyResult/Single/Sections/Owner/Update/messages.ts
- src/components/KeyResult/Single/Sections/Owner/Update/queries.gql
- src/components/KeyResult/Single/Sections/Owner/Update/search.tsx
- src/components/KeyResult/Single/Sections/Owner/Update/user-list-skeleton.tsx
- src/components/KeyResult/Single/Sections/Owner/Update/user-list.tsx
- src/components/KeyResult/Single/Sections/Owner/Update/wrapper.tsx
- src/components/KeyResult/Single/Sections/Owner/index.ts
- src/components/KeyResult/Single/Sections/Owner/messages.ts
- src/components/KeyResult/Single/Sections/Owner/owner.tsx
- src/components/KeyResult/Single/Sections/Owner/wrapper.tsx
- src/components/KeyResult/Single/Sections/Timeline/Cards/CheckIn/check-in.tsx
- src/components/KeyResult/Single/Sections/Timeline/Header/DeleteAlert/delete-alert.spec.tsx
- src/components/Objective/AccordionItem/queries.gql
- src/components/User/NamedAvatar/messages.ts
- src/components/User/NamedAvatar/named-avatar.tsx
- src/state/hooks/useConnectionEdges/hook.ts
- src/themes/preset-base/components/input.ts
This PR adds the owner update to our key-result drawer.
> Feature: Key Result owner update

- lang/pt-BR.json
- src/components/KeyResult/Single/Sections/Goal/wrapper.tsx
- src/components/KeyResult/Single/Sections/Owner/Update/queries.gql
Fixes some issues in our editable fields for the Key Result Drawer
> Bugfix: Key Result editable fields

- package-lock.json
- package.json
- src/components/Base/TooltipWithDelay/tooltip-with-delay.tsx
A workaround while [@chakra-ui#3951](https://github.com/chakra-ui/chakra-ui/issues/3951) remains open.
> Bugfix: Chakra's Tooltip Bug workaround

- .idea/vcs.xml
- src/components/Base/SliderWithHoverThumb/slider-with-hover-thumb.tsx
- src/components/KeyResult/ActiveAndOwnedByUser/queries.gql
- src/components/KeyResult/NotActiveAndOwnedByUser/queries.gql
- src/components/KeyResult/ProgressSlider/slider.tsx
- src/components/KeyResult/Single/Sections/Timeline/Cards/CheckIn/comment.tsx
- src/components/KeyResult/constants.ts
- src/components/KeyResult/types.ts
- src/components/Objective/AccordionItem/queries.gql
This PR adds the reversed key-result feature
> Feature: Reversed Key Result

- src/components/Base/EmptyState/empty-state.tsx
- src/components/KeyResult/Single/Sections/Owner/Update/user-list.tsx
- src/components/Page/Team/ChildTeams/wrapper.tsx
- src/components/Page/Team/team.tsx
- src/components/User/List/wrapper.tsx
This PR fixes some team page bugs
> Bugfix: Team page

- src/components/Report/TeamsOverview/Body/Table/Body/Columns/NameAndOrder/name-and-order.tsx
Adds the team page link to our dashboard team list
> Feature: Dashboard team link

- src/components/Base/ConfirmationDialog/dangerous-message.tsx
- src/components/Objective/AccordionItem/Menu/messages.ts
- src/components/Objective/AccordionItem/Menu/option-create-key-result.tsx
- src/components/Objective/AccordionItem/Menu/option-delete-objective.tsx
- src/components/Objective/AccordionItem/Menu/option-update-objective.tsx
- src/components/Objective/AccordionItem/Menu/queries.gql
- src/components/Objective/AccordionItem/Menu/wrapper.tsx
- src/components/Team/ActiveObjectives/queries.gql
- src/components/Team/ActiveObjectives/wrapper.tsx
- src/state/recoil/team/active-objectives.ts
This PR adds the delete objective feature
> Feature: Delete Objective

- lang/pt-BR.json
- src/components/Cycle/types.ts
- src/components/KeyResult/ActiveAndOwnedByUser/queries.gql
- src/components/KeyResult/CheckInForm/queries.gql
- src/components/KeyResult/List/Body/Columns/KeyResult/key-result.tsx
- src/components/KeyResult/NotActiveAndOwnedByUser/queries.gql
- src/components/KeyResult/Single/Sections/Timeline/Cards/CheckIn/check-in.tsx
- src/components/KeyResult/Single/Sections/Timeline/queries.gql
- src/components/KeyResult/Single/Sections/Title/title.tsx
- src/components/KeyResult/types.ts
- src/components/Objective/AccordionItem/Item/Button/queries.gql
- src/components/Objective/AccordionItem/Item/Button/view-mode.tsx
- src/components/Objective/AccordionItem/Item/Panel/queries.gql
- src/components/Objective/types.ts
- src/components/Report/CompanyProgressOverview/Body/Stamps/Company/company.tsx
- src/components/Report/CompanyProgressOverview/Body/Stamps/ProgressIncrease/progress-increase.tsx
- src/components/Report/CompanyProgressOverview/queries.gql
- src/components/Report/TeamsOverview/Body/Table/Body/Columns/ProgressIncrease/progress-increase.tsx
- src/components/Report/TeamsOverview/queries.gql
- src/components/Report/TeamsOverview/teams-overview.tsx
- src/components/Team/ActiveObjectives/queries.gql
- src/components/Team/types.ts
- src/components/types.ts
- src/state/recoil/key-result/check-in/latest.ts
This PR adds the ability to display only active items in the dashboard
> Feature: Displays only active items in dashboard

- src/components/KeyResult/Single/Drawer/drawer.tsx
- src/components/KeyResult/Single/Sections/AddComment/input.tsx
- src/components/KeyResult/Single/Sections/Timeline/Cards/Comment/comment.tsx
- src/components/User/AllReachableUsers/queries.gql
This PR implements mentions in Key Result comments. It's now possible to tag someone (and in the future tag a team).
Here are some pictures of what the implementation looks like:
Start the application, open `Meus Key Results`, click in the first key result then write a comment.
> Feat: comment mentions (aditional PR)

- src/components/Base/ConfirmationDialog/wrapper.tsx
- src/components/Base/ConfirmationModal/confirmation-modal.tsx
- src/components/KeyResult/Single/Drawer/drawer.tsx
- src/components/KeyResult/Single/Sections/AddComment/input.tsx
- src/components/KeyResult/Single/Sections/AddComment/messages.ts
- src/components/KeyResult/Single/Sections/Timeline/Cards/Comment/comment.tsx
This PR fixes some minor issues in the Mentions feature. We've applied some fixes in color, spacing and other relevant areas of our feature.
> Bugfix: Mentions QA

- src/components/KeyResult/Single/Sections/AddComment/input.tsx
> style(components/keyresult/comments): linting fixes

- src/components/KeyResult/Single/Sections/Timeline/Cards/Comment/comment.tsx
> fix(infra/notification/created-comment): regex

- src/components/Page/Team/Header/menu.tsx
- src/components/Team/ActiveObjectives/wrapper.tsx
> bugfix(components/Team/ActiveObjectives): fix wrong paths and variables

- lang/en-US.json
- lang/pt-BR.json
- src/components/Page/Team/ChildTeams/wrapper.tsx
- src/components/User/SelectFromList/wrapper.tsx
Some corrections before production
> Chore: prepare for prod

- src/state/hooks/useAmplitude/ensure-initialized.ts
> feat(amplitude): allow and capture utm tags in url

- src/components/Base/AuthzGatekeeper/authz-gatekeeper.tsx
- src/pages/_app.tsx
> bugfix(pages): auth0 correct redirectUri

- src/components/User/AllReachableUsers/wrapper.tsx
> bugfix(components/AllReachableUsers): team select becaming infinite loop

- .github/workflows/deploy-to-canary.yml
> ci(workflows): deploy to canary

- .github/workflows/deploy-to-canary.yml
> Ci: deploy to canary

- src/components/KeyResult/Single/Sections/Checklist/checklist.tsx
> feat(components/checklist): remove limit of checkmarks

- src/components/User/NamedAvatar/name-with-avatar.tsx
Lazy load avatar images
Open the team page and check if it solves the blocking time.
> Add lazy load to avatar

- .github/workflows/deploy-to-canary.yml
> ci(workflows/deploy-to-canary): remove docker cache

- .husky/pre-push
- .lintstagedrc
Remove lint from pre-commit action and move it to pre-push
Improve dev experience linting only before pushing to remote.
> Remove lint from pre-commit action and move it to pre-push

- .github/workflows/deploy-to-canary.yml
> ci: deploy when tag is pushed

- .github/workflows/deploy-to-canary.yml
> CI: manual run

- src/components/KeyResult/Single/Sections/Checklist/ActionButtons/change-assigned.tsx
- src/components/User/NamedAvatar/name-with-avatar.tsx
Add lazy behavior to task assign component
> Add lazy behavior to task assign component

- src/components/User/NamedAvatar/name-with-avatar.tsx
> Fix avatar logic

- src/components/Base/EditableInputField/editable-input-field.tsx
- src/components/KeyResult/Single/Sections/Checklist/ActionButtons/create-checkmark.tsx
- src/components/KeyResult/Single/Sections/Checklist/OptionBar/empty-checklist.tsx
- src/components/KeyResult/Single/Sections/Checklist/OptionBar/wrapper.tsx
- src/components/KeyResult/Single/Sections/Checklist/toggle-collapse.tsx
- src/components/KeyResult/Single/Sections/Checklist/wrapper.tsx
- src/components/KeyResult/Single/Sections/Heading/interface.ts
- src/components/KeyResult/Single/Sections/Heading/wrapper.tsx
- src/components/Page/MyThings/ActiveCycles/my-tasks/queries.gql
- src/components/Page/MyThings/ActiveCycles/my-tasks/tasks.tsx
Allow users to create new tasks from the "my things" page
> Add tasks from my things page

- src/components/KeyResult/List/Body/Columns/Owner/skeleton.tsx
Bugfix to allow deploy to canary
> bugfix(components/kr/list/columns/owner): remove old property in skeleton

- .env.example
- .gitignore
- lib/apollo/index.ts
- manifests/canary/canary-deployment.yaml
- manifests/stable/deployment.yaml
- next.config.js
- package-lock.json
- package.json
- sentry.client.config.ts
- sentry.properties
- sentry.server.config.ts
- src/pages/_error.tsx
- tsconfig.json
> Feat: sentry

- sentry.client.config.ts
> bugfix(sentry): remove unused BrowserTracing

- lang/en-US.json
- lang/pt-BR.json
- package-lock.json
- src/components/KeyResult/Single/Sections/Checklist/ActionButtons/messages.ts
> fix(my-things) changing add task button description

- manifests/ingress-route.yaml
> bugfix(manifests/ingres-route): use tls 1.2 or above

- bin/install.sh
- package-lock.json
- package.json
This simplifies the process of installing all dependencies needed to execute the project for the first time.
> Feat: install script

- package.json
- waypoint.hcl
Corrige o deploy pra prod, ainda do script "manual".
> bugfix: deploy to prod (temporario)

- src/components/Report/BoardsOverview/KeyResultListing/index.tsx
- src/state/hooks/useConfidenceTag/hook.ts
- src/state/hooks/useEvent/event-type.ts
- src/state/hooks/useEvent/event.ts
- src/state/hooks/useEvent/events/opened-key-result-report-confidance-data.ts
> Feat: amplitude event when open confidence krs report 

- lang/en-US.json
- lang/pt-BR.json
- manifests/canary/canary-deployment.yaml
- manifests/stable/deployment.yaml
- next.config.js
- src/components/Report/TeamsOverview/Body/Table/Body/Columns/PositionBedge/position-bedge.tsx
- src/components/Report/TeamsOverview/Body/Table/Body/body.tsx
- src/components/Report/TeamsOverview/messages.ts
- src/components/Report/TeamsOverview/teams-overview.tsx
- src/components/Team/hooks/getGamificationDetails/get-gamification-details.ts
- src/components/Team/hooks/getGamificationDetails/index.ts
- src/components/Team/hooks/index.ts
- src/config.ts
> refactor(ranking): toggle gamification based on env ids

- src/components/Objective/Accordion/Item/Button/messages.ts
- src/components/Objective/IndividualPlan/individual-plan.tsx
- src/components/Objective/IndividualPlan/messages.ts
- src/components/Objective/IndividualPlan/queries.gql
- src/components/User/DetailedHeader/detailed-header.tsx
- src/components/User/Me/queries.gql
> Bugfix: personal objective permission

- lang/en-US.json
- lang/pt-BR.json
> fix(lang): adding translations

- src/components/KeyResult/InsertDrawer/wrapper.tsx
- src/components/Objective/IndividualPlan/individual-plan.tsx
> fix(individual-plan/amplitude): fix amplitude events for personal things tab and key result creation

- src/components/KeyResult/ActiveAndOwnedByUser/queries.gql
- src/components/KeyResult/NotActiveAndOwnedByUser/queries.gql
- src/components/KeyResult/Single/Sections/Owner/wrapper.tsx
- src/components/KeyResult/types.ts
- src/components/Objective/Accordion/Item/Panel/queries.gql
> fix(key-result/support-team): change definition of individual kr

- src/components/User/Logout/logout.tsx
> fix(logout): redirect user to location origin

- src/components/Base/NotificationsButton/notifications-button.tsx
- src/components/KeyResult/CheckInForm/form.tsx
- src/components/KeyResult/Single/Drawer/drawer.tsx
- src/components/Notifications/CheckInNotifications/NotificationKeyResult/index.tsx
- src/components/Notifications/CheckInNotifications/index.tsx
- src/components/Notifications/Modal/index.tsx
- src/components/Notifications/Modal/queries.gql
- src/state/hooks/useEvent/event-type.ts
- src/state/hooks/useEvent/event.ts
- src/state/hooks/useEvent/events/notification-bell-data.ts
- src/state/hooks/useEvent/events/notification-check-in-click-data.ts
- src/state/recoil/notifications/created-by-check-in-notification.ts
- src/state/recoil/notifications/index.ts
> feat(check-in-notifications): adding amplitude events

- src/components/Icon/Clock/clock.tsx
> fix(last-update/icon): intermittent appearence

- src/components/Base/NotificationsButton/notifications-button.tsx
- src/components/Notifications/Modal/index.tsx
- src/components/Notifications/NotificationsList/notifications-list.tsx
- src/state/hooks/useEvent/event-type.ts
- src/state/hooks/useEvent/event.ts
- src/state/hooks/useEvent/events/notification-card-click-data.ts
- src/state/hooks/useEvent/events/tab-check-in-click-data.ts
- src/state/hooks/useEvent/events/tab-notification-click-data.ts
> feat(amplitude): adding events to the notification list

- .github/PULL_REQUEST_TEMPLATE.md
Establish a (not so) new pull request template to better document our process 
It will give more context whenever we need to revisit our previous steps.
N/A
N/A
N/A
> refactor(): pull request template

- src/components/KeyResult/Single/Drawer/Body/body.tsx
- src/components/KeyResult/Single/Drawer/content.tsx
- src/components/KeyResult/Single/Drawer/drawer.tsx
- src/components/KeyResult/Single/Drawer/queries.gql
- src/components/KeyResult/Single/Sections/Objective/messages.ts
- src/components/KeyResult/Single/Sections/Objective/objective.tsx
- src/components/KeyResult/Single/Sections/Title/actions.tsx
- src/components/KeyResult/Single/Sections/Title/messages.ts
- src/components/KeyResult/Single/Sections/Title/title.tsx
Include in the key-result drawer a section containing the objective details.
I modified an objective section that was already in the key-result drawer code, but was not being used.
Open a key-result.
- [`BUD22-427`](https://getbud.atlassian.net/jira/software/projects/BUD22/boards/16?selectedIssue=BUD22-427)
> refactor(kr-drawer) add objective section in KR drawer

- src/components/Icon/CircleArrowRight/circle-arrow-right.tsx
- src/components/Icon/CircleArrowRight/index.ts
- src/components/Icon/index.ts
- src/components/Page/Team/Tabs/content/messages.ts
- src/components/Page/Team/Tabs/content/retrospective-tab-content.tsx
- src/components/Page/Team/Tabs/tabs-menu.tsx
This PR implements the QA of the related PR.
Just style tweaks.
-
- [`BUD22-454`](https://getbud.atlassian.net/jira/software/projects/BUD22/boards/16?selectedIssue=BUD22-454)
- [`execution-mode#308`](https://github.com/budproj/execution-mode/pull/308)
> QA_01: Routines Tab Page

- src/components/Base/SupportButton/constants.ts
Te helpdesk link were outdated
Update the helpdesk link
- [`BUD22-468`](https://getbud.atlassian.net/browse/BUD22-468)
> chore(helpdesk): update helpdesk link

- manifests/stable/deployment.yaml
> chore(maintenance): active maintenance

- manifests/stable/deployment.yaml
Reverts budproj/execution-mode#311
> Revert "chore(maintenance): active maintenance"

- src/components/Report/hooks/getCompanyCycles/get-company-cycles.gql
We detected a query blocking a lot of resources and one of the issues was the cycle delta query.
Remove inactive cycles from dashboard query
> perf(company-cycles): remove unactive cycles

- src/components/Base/RadioButton/radio-card.tsx
- src/components/Base/RoutineFormActionsProvider/routine-form-actions-provider.tsx
- src/components/Routine/Drawer/Base/drawer.tsx
- src/components/Routine/Drawer/Base/submit-answer-button.tsx
- src/components/Routine/Drawer/Questions/EmojiScale/index.tsx
- src/components/Routine/Drawer/Questions/LongText/index.tsx
- src/components/Routine/Drawer/Questions/ReadingText/index.tsx
- src/components/Routine/Drawer/Questions/RoadBlock/index.tsx
- src/components/Routine/Drawer/Questions/ValueRange/index.tsx
- src/components/Routine/Drawer/Questions/base.tsx
- src/components/Routine/Drawer/Questions/types.ts
- src/components/Routine/Retrospective/wrapper.tsx
- src/components/Routine/hooks/getRoutineForm/get-routine-form.tsx
- src/components/Routine/hooks/setRoutineFormAnswers/messages.ts
- src/components/Routine/hooks/setRoutineFormAnswers/set-routine-form-answers.tsx
- src/pages/_app.tsx
- src/state/recoil/routine/retrospective-routine-answers.ts
- [`BUD22-494`](https://getbud.atlassian.net/browse/BUD22-494)
- [`routines-microservice#37`](https://github.com/budproj/routines-microservice/pull/37)
> qa(routines/form)

- src/components/Notifications/Modal/index.tsx
- src/components/Page/Dashboard/dashboard.tsx
- src/components/Page/Team/Tabs/tabs-menu.tsx
- src/components/Page/Team/Tabs/wrapper.tsx
Removing routines because alphabot asked!
using use gamification in the routines sections.
> feat(routine): removing routine to the companys that does not like it

- src/components/Report/MetricsOverview/MetricTeamRow/index.tsx
Many requests were being executed when the user went from the Dashboard to the team page through the Team Climate panel.
Replacement of the intlLink by the next router, which allows for greater intelligence in the refetch of requests.
> fix(performance)

- src/components/Base/NoticesBanner/index.tsx
- src/components/Routine/RetrospectiveTab/Answers/index.tsx
- src/components/Routine/RetrospectiveTab/Comments/CommentCard/index.tsx
- src/components/Routine/RetrospectiveTab/Comments/CommentInput/custom-mentions-input.tsx
- src/state/hooks/useEvent/event-type.ts
- src/state/hooks/useEvent/event.ts
- src/state/hooks/useEvent/events/learn-more-banner-notices-click-data.ts
* Track "Learn More" click event on noticies banner
* Improve comment card spacing in routines
* Consider the userCompany as a user team
> fix(routines)

- src/components/Routine/RetrospectiveTab/Answers/index.tsx
> fix(answer-now-button): bugfix answer now button including userteamids

- src/components/Page/Team/Highlights/modals/UsersTeamList/index.tsx
- src/components/Page/Team/Highlights/modals/UsersTeamList/messages.ts
- src/components/User/hooks/getUserDetails/get-user-details.gql
> feat(team-highlights): adding clicks to users list

- src/components/Page/Team/Highlights/highlight-card.tsx
- src/components/Page/Team/Highlights/highlight-section.tsx
- src/components/Report/MetricsOverview/MetricTeamRow/index.tsx
- src/components/Report/MetricsOverview/index.tsx
- src/components/Routine/RetrospectiveTab/Answers/AnswerContent/AnswerCards/RoadblockAnswerCard/roadblock.tsx
- src/components/Routine/RetrospectiveTab/Answers/utils/contants.ts
- src/state/hooks/useEvent/event-type.ts
- src/state/hooks/useEvent/event.ts
- src/state/hooks/useEvent/events/team-highlight-click-data.ts
> feat(highlights-events): adding events and roadblock color fix

- .github/workflows/nextjs_bundle_analysis.yml
- package.json
> CI: add nextjs bundle analysis

- .github/workflows/nextjs_bundle_analysis.yml
- package.json
> Ci: bundle analysis

- .github/workflows/test-pull-request.yml
> CI: pr check

- src/components/Team/IndicatorsAccordion/AccordionButton/index.tsx
- src/components/Team/IndicatorsTable/Columns/key-results-checklists.tsx
- src/components/Team/IndicatorsTable/Columns/key-results-overview.tsx
- src/components/Team/IndicatorsTable/Columns/last-retrospective-answer.tsx
- src/components/Team/IndicatorsTable/wrapper.tsx
- src/components/User/KeyResultsOverview/key-results-overview.tsx
- src/components/User/KeyResultsOverview/wrapper.tsx
- src/components/User/LastRetrospectiveAnswerOverview/LastRetrospectiveAnswer/wrapper.tsx
- src/components/User/LastRetrospectiveAnswerOverview/wrapper.tsx
- src/state/hooks/useEvent/event-type.ts
- src/state/hooks/useEvent/event.ts
- src/state/hooks/useEvent/events/indicator-accordion-button-click-data.ts
- src/state/hooks/useEvent/events/indicator-check-list-click-data.ts
- src/state/hooks/useEvent/events/indicator-progress-click-data.ts
- src/state/hooks/useEvent/events/indicator-report-download-click-data.ts
- src/state/hooks/useEvent/events/indicator-routine-click-data.ts
> feat(indicators-event): adding indicators events

- lang/en-US.json
- lang/pt-BR.json
- src/components/Team/IndicatorsTable/Columns/last-access.tsx
- src/components/Team/IndicatorsTable/Columns/messages.ts
The interface was not prepared for cases where a user had never accessed the platform.
Creating a specific text for "never_accessed" users
> fix(analytics-teamindicators)

- lang/en-US.json
- lang/pt-BR.json
- src/components/Page/Team/Indicators/messages.ts
- src/components/Page/Team/Indicators/wrapper.tsx
> feat(analytics/tooltips) create tooltip messages

- src/components/Page/Team/team.tsx
> fix(create-team) consider the multiple traductions to OKR tab page

- src/components/Routine/RetrospectiveTab/Answers/index.tsx
- src/components/Routine/RetrospectiveTab/retrospective-tab-content.tsx
- src/components/Routine/hooks/useAnswerSummaryPagination/use-answer-summary-pagination.tsx
> fix(answer-summary-users) allow load no current user answers

- src/components/Routine/RetrospectiveTab/Comments/CommentCard/index.tsx
- src/components/Routine/RetrospectiveTab/Comments/CommentInput/custom-mentions-input.tsx
> fix(comment): fixing comment mentions and comment line break

- src/components/Report/MetricsOverview/MetricTeamRow/index.tsx
- src/components/Report/MetricsOverview/index.tsx
- src/components/Routine/RetrospectiveTab/RoutinesOverview/index.tsx
> fix(dashboard-routines) enable receive routines overview as undefined

- src/components/Base/NoticesBanner/index.tsx
- src/components/Base/NoticesBanner/messages.ts
> feat(spotlight): add spotlight banner

- src/components/KeyResult/Single/Sections/AddComment/add-comment.tsx
- src/state/hooks/useEvent/events/create-draft-feedback-click-data.ts
> fix(events) adding feedback draft events

- src/components/KeyResult/Single/Sections/KeyResultSummarizeSection/index.tsx
> fix(summarize-button): fixing wand hover button

- src/components/KeyResult/Single/Drawer/Body/body.tsx
- src/components/KeyResult/Single/Sections/AddComment/add-comment.tsx
- src/components/KeyResult/Single/Sections/KeyResultHistory/index.tsx
- src/components/KeyResult/Single/Sections/KeyResultHistory/messages.ts
- src/components/KeyResult/Single/Sections/KeyResultSummarizeSection/index.tsx
- src/components/KeyResult/Single/Sections/KeyResultSummarizeSection/messages.ts
- src/components/KeyResult/Single/Sections/Timeline/timeline.tsx
- src/components/Page/Team/Indicators/CSVDownload/index.tsx
- src/components/Page/Team/Indicators/wrapper.tsx
- src/components/Page/Team/Tabs/tabs-menu.tsx
> fix(new-and-beta-button): adding beta button and removing new buttons

- src/components/Objective/Accordion/Item/wrapper.tsx
> fix(draft-objective): changing dashed bottom border

- src/state/hooks/useCycleObjectives/hook.ts
> fix(objective): fixing objectives order in the team page

- src/components/KeyResult/Single/Sections/KeyResultSummarizeSection/index.tsx
> fixing user id to myself id

- src/components/Notifications/NotificationsList/Card/CommentOnRoutine/index.tsx
> fixing notification bug

- src/components/Notifications/NotificationsList/Card/CommentOnRoutine/index.tsx
> fixing link

- lang/en-US.json
- lang/pt-BR.json
- src/components/Base/NoticesBanner/index.tsx
- src/components/Base/NoticesBanner/messages.ts
> feat(know-draft-mode-banner) create banner

- src/components/MissionControl/BestPracticesLighthouse/index.tsx
- src/components/MissionControl/Tasks/empty-state-tasks-list.tsx
> fix tooltip and new text

- src/components/MissionControl/Tasks/wrapper.tsx
> fix(filter-tasks) .

- src/components/Page/Dashboard/dashboard.tsx
- src/components/Page/Dashboard/messages.ts
- src/components/Page/Dashboard/queries.gql
- src/components/Report/OverviewSummary/overview-summary.tsx
- src/components/User/Profile/TeamsMenu/index.tsx
- src/components/User/Profile/TeamsMenu/queries.gql
> feat(overview): adding overview to contemplate teams too

- src/components/User/Profile/TeamsMenu/queries.gql
> fix(main-team): fixing request to get cycle and progress

- lang/en-US.json
- lang/pt-BR.json
- src/components/Base/NoticesBanner/index.tsx
- src/components/Base/NoticesBanner/messages.ts
> feat(webnar-banner) create notice banner to webnar

- src/components/KeyResult/hooks/getKeyResults/get-key-results.gql
- src/components/KeyResult/hooks/getKeyResults/get-key-results.ts
- src/components/Page/Dashboard/dashboard.tsx
- src/components/Report/BoardsOverview/index.tsx
- src/components/Report/CompanyProgressOverview/types.ts
- src/components/Report/OverviewSummary/overview-summary.tsx
- src/components/Report/hooks/getHealthConfidenceQuantities/get-health-confidence-quantities.gql
- src/components/Report/hooks/getHealthConfidenceQuantities/get-health-confidence-quantities.ts
- src/components/Team/types.ts
> feat(boards-overview): fixing boards overview

- src/components/Base/NoticesBanner/index.tsx
> refactor(webnar-banner) remove outdated webnar notice banner

- src/components/Page/Dashboard/dashboard.tsx
> fix(dashboard-responsitivy) improve the app layout for many browsers

- src/components/Base/TasksCard/messages.ts
- src/components/Base/TasksCard/task-card-action.tsx
> fix(task): fixing done task text

- src/components/Base/MainAppBar/TeamHoverMenu/team-hover-menu.tsx
- src/components/Base/NoticesBanner/index.tsx
- src/components/Base/NoticesBanner/messages.ts
> feat(notices-banner): adding nps from october 2023

- src/components/Page/Dashboard/dashboard.tsx
- src/components/User/Profile/wrapper.tsx
> fixing the bug that causes the loop

- src/components/Page/Dashboard/dashboard.tsx
> fixing feature flag

- src/components/Page/Dashboard/dashboard.tsx
- src/components/User/Profile/TeamsMenu/index.tsx
> chore: fix list users on dashboard

- src/components/Page/Dashboard/dashboard.tsx
> chore: fix media queries

- src/components/Objective/Accordion/Menu/wrapper.tsx
> fix(delete-objective-permission): fixing to allow all but teammember

- src/components/Page/Dashboard/queries.gql
> changing limit to teams that appears in the select dashboard menu

- src/components/User/Profile/TeamsMenu/index.tsx
> fixing scroll team menu

- src/components/Page/Dashboard/dashboard.tsx
- src/components/User/Profile/TeamsMenu/index.tsx
> fix: dashboard responsivity

- src/components/Base/NoticesBanner/index.tsx
- src/components/Base/NoticesBanner/messages.ts
> feat(notices-banner-nps) update NoticesBanner component styling and text

- src/components/Report/BoardsOverview/KeyResultsListingTable/index.tsx
> chore: update loading logic

- src/components/Report/BoardsOverview/KeyResultsListingTable/index.tsx
Reverts budproj/execution-mode#487
> Revert "chore: update loading logic"

- src/components/Page/Team/queries.gql
> fix(krs-policy) add keyResults policy create to team queries

- src/components/Page/Team/Tabs/tabs-menu.tsx
> feat(flag): add feature flag in code

- src/components/KeyResult/Single/Sections/Checklist/check-mark.tsx
- src/state/recoil/key-result/checklist.ts
> fixing checkmark in key result drawer

- src/components/KeyResult/Single/Sections/Checklist/check-mark.tsx
> fixing update checkmark progress

- src/components/TaskManagement/TaskDrawer/index.tsx
> fix task drawer

- src/components/KeyResult/Single/Sections/Timeline/Cards/Base/base.tsx
- src/components/KeyResult/Single/Sections/Timeline/Cards/Comment/Default/index.tsx
- src/components/Page/Team/Tabs/wrapper.tsx
- src/components/Routine/hooks/deleteComment/delete-comment.ts
- src/components/Routine/hooks/deleteComment/index.ts
- src/components/TaskManagement/TaskDrawer/Timeline/TaskCommnet/index.tsx
> feat(task): adding delete task comment function

- src/components/KeyResult/Single/Sections/Owner/support-team-field.tsx
- src/components/KeyResult/Single/Sections/Owner/support-team-popover.tsx
- src/components/TaskManagement/Board/hooks/use-load-owners-and-support-team.ts
- src/components/TaskManagement/Board/wrapper.tsx
- src/components/TaskManagement/TaskDrawer/index.tsx
- src/state/recoil/task-management/board/constants.ts
- src/state/recoil/task-management/board/owners-and-support-team-task.ts
> fixing support team and owners

- src/components/Page/Dashboard/dashboard.tsx
> perf(mc): remove mission control

- src/components/KeyResult/types.ts
- src/components/Notifications/CheckInNotifications/NotificationKeyResult/index.tsx
- src/components/Notifications/CheckInNotifications/index.tsx
- src/components/Notifications/Modal/index.tsx
- src/components/Notifications/Modal/queries.gql
- src/components/Page/Dashboard/dashboard.tsx
> perf(kr not): front end of key results in notifications

- src/components/KeyResult/types.ts
- src/components/Notifications/CheckInNotifications/NotificationKeyResult/index.tsx
- src/components/Notifications/CheckInNotifications/index.tsx
- src/components/Notifications/Modal/index.tsx
- src/components/Notifications/Modal/queries.gql
- src/components/Page/Dashboard/dashboard.tsx
- src/components/Team/CardList/Card/card.tsx
- src/components/Team/CardList/card-list.tsx
- src/components/Team/CardList/queries.gql
> perf(query): front update so it request new resolvers

- src/components/KeyResult/types.ts
- src/components/Notifications/CheckInNotifications/NotificationKeyResult/index.tsx
- src/components/Notifications/CheckInNotifications/index.tsx
- src/components/Notifications/Modal/index.tsx
- src/components/Notifications/Modal/queries.gql
- src/components/Page/Dashboard/dashboard.tsx
- src/components/Report/TeamsOverview/Body/Table/Body/Columns/Progress/progress.tsx
- src/components/Report/TeamsOverview/Body/Table/Body/Columns/ProgressIncrease/progress-increase.tsx
- src/components/Report/TeamsOverview/queries.gql
- src/components/Report/TeamsOverview/teams-overview.tsx
- src/components/Team/CardList/Card/card.tsx
- src/components/Team/CardList/card-list.tsx
- src/components/Team/CardList/queries.gql
> perf(query): change type so it works with backend get_company_teams

- src/components/KeyResult/types.ts
- src/components/Notifications/CheckInNotifications/NotificationKeyResult/index.tsx
- src/components/Notifications/CheckInNotifications/index.tsx
- src/components/Notifications/Modal/index.tsx
- src/components/Notifications/Modal/queries.gql
- src/components/Page/Dashboard/dashboard.tsx
- src/components/Page/Dashboard/queries.gql
- src/components/Report/TeamsOverview/Body/Table/Body/Columns/Progress/progress.tsx
- src/components/Report/TeamsOverview/Body/Table/Body/Columns/ProgressIncrease/progress-increase.tsx
- src/components/Report/TeamsOverview/queries.gql
- src/components/Report/TeamsOverview/teams-overview.tsx
- src/components/Team/CardList/Card/card.tsx
- src/components/Team/CardList/card-list.tsx
- src/components/Team/CardList/queries.gql
> [To be Deployed] Perf/improve server response time in pannel

- src/components/Base/NoticesBanner/index.tsx
- src/components/Base/NoticesBanner/messages.ts
> adding banner

- src/components/Base/MainAppBar/MenuItem/menu-item.tsx
- src/components/Base/MainAppBar/TeamHoverMenu/team-hover-menu.tsx
- src/pages/_app.tsx
- src/state/hooks/useEvent/event-type.ts
- src/state/hooks/useEvent/event.ts
- src/state/hooks/useEvent/events/main-menu-tabs-click.data.ts
- src/state/hooks/useEvent/events/main-menu-tabs-my-things-click.data.ts
- src/state/hooks/useEvent/events/main-menu-tabs-panel-click.data.ts
- src/state/hooks/useEvent/events/main-menu-tabs-teams-click.data.ts
> adding events and removing banner

- src/components/Page/Team/Tabs/tabs-menu.tsx
- src/components/Page/Team/Tabs/wrapper.tsx
> adding tasks tabs to everyone

- src/components/Page/Dashboard/dashboard.tsx
- src/components/Page/Dashboard/queries.gql
> fixing progress

- src/components/Base/KanbanTaskCard/kanban-task-card-content.tsx
- src/components/Page/Dashboard/queries.gql
- src/components/TaskManagement/TaskDrawer/Timeline/index.tsx
- src/components/TaskManagement/TaskDrawer/title-section.tsx
- src/components/Team/hooks/getTeamActiveObjectives/queries.gql
- src/state/hooks/useCycleObjectives/hook.ts
> fixing objective order and company progress in panel

- src/components/Page/Dashboard/dashboard.tsx
- src/components/Routine/RetrospectiveTab/retrospective-tab-content.tsx
> fixing retro state management

- src/components/Report/TeamsOverview/queries.gql
> removing unnecessary user field

- src/components/Base/MainAppBar/TeamHoverMenu/team-hover-menu.tsx
- src/components/Base/NoticesBanner/index.tsx
- src/components/Base/NoticesBanner/messages.ts
- src/components/Page/MyThings/ActiveCycles/my-tasks/index.tsx
- src/components/Page/MyThings/ActiveCycles/my-tasks/queries.gql
- src/pages/_app.tsx
> changing to keyresultstatus query

- .github/workflows/deploy.yaml
- Dockerfile
> Feat: new deploy.

- src/components/KeyResult/InsertDrawer/Form/wrapper.tsx
> fixing key-result add

- src/components/Cycle/hooks/getCycles/get-cycles.gql
- src/components/Routine/RetrospectiveTab/Answers/index.tsx
- src/components/Routine/RetrospectiveTab/retrospective-tab-content.tsx
- src/components/Routine/hooks/useAnswerSummaryPagination/use-answer-summary-pagination.tsx
- src/components/Team/CardList/Card/card.tsx
> adding-view-button

- src/components/Page/Dashboard/dashboard.tsx
- src/components/Page/Dashboard/queries.gql
- src/components/Report/OverviewSummary/overview-summary.tsx
- src/components/Team/types.ts
- src/components/User/Profile/TeamsMenu/queries.gql
> fixing to progress with children in the dashboard

- src/components/Team/Tag/tag.tsx
- src/components/User/TeamTags/team-tags.tsx
- src/components/User/Teams/add-team.tsx
- src/state/recoil/user/add-team-loading.ts
> add disabled button when loading team

- .env.example
- next.config.js
- src/config.ts
- src/pages/_document.tsx
> adding clarity via script

- src/components/KeyResult/InsertDrawer/Form/okr-example-link.tsx
- src/components/KeyResult/List/Body/GuideListCreateOKR/guide-list-create-okr.tsx
> Fix: okr samples external links.

- .github/PULL_REQUEST_TEMPLATE.md
- src/components/KeyResult/InsertDrawer/Form/format-masked-input.tsx
- src/components/KeyResult/InsertDrawer/Form/queries.gql
- src/components/KeyResult/InsertDrawer/Form/wrapper.tsx
- src/components/KeyResult/Single/Drawer/queries.gql
> fix key result type change when update

- src/components/KeyResult/InsertDrawer/Form/description.tsx
- src/components/KeyResult/Single/Sections/Description/description.tsx
Adding breakline to kr description.
Add property whitespace pre-line to text and textarea, making components recognizing breakline.
- [`BUD22-123`](https://www.notion.so/budops/Formata-o-quebrada-na-descri-o-do-KR-b863f24831c7401c8f3db868d0111cc6?pvs=4)
> adding breakline to kr description

- src/components/Base/NoticesBanner/index.tsx
Banner was not saving on close
> Fix: banner.

- src/components/Page/MyThings/ActiveCycles/company-okrs.tsx
- Hide task for re-implement this component with new api.
> hide personal tasks for future changes

- src/components/TaskManagement/InsertDrawer/Form/wrapper.tsx
- Bugfix = fix insert drawer for task not being opened
> fix addTask error

- src/components/KeyResult/Single/Sections/Checklist/ActionButtons/delete-task.tsx
- src/components/KeyResult/Single/Sections/Checklist/inline-tasklist.tsx
- src/components/KeyResult/Single/Sections/Checklist/wrapper.tsx
- src/components/Page/MyThings/ActiveCycles/my-tasks/tasks.tsx
- src/components/Page/Team/Tabs/content/board-tab-content.tsx
- src/components/TaskManagement/Board/components/column.tsx
- src/components/TaskManagement/Board/components/task.tsx
- src/components/TaskManagement/Board/hooks/use-column-tasks.ts
- src/components/TaskManagement/Board/wrapper.tsx
- src/components/TaskManagement/InsertDrawer/Form/owner.tsx
- src/components/TaskManagement/InsertDrawer/Form/wrapper.tsx
- src/components/TaskManagement/TaskDrawer/OwnerSection/index.tsx
- src/components/TaskManagement/TaskDrawer/SupportTeamField/RichTooltips/index.ts
- src/components/TaskManagement/TaskDrawer/SupportTeamField/RichTooltips/support-team.tsx
- src/components/TaskManagement/TaskDrawer/SupportTeamField/SupportTeamPopOver/index.ts
- src/components/TaskManagement/TaskDrawer/SupportTeamField/SupportTeamPopOver/support-team-popover.tsx
- src/components/TaskManagement/TaskDrawer/SupportTeamField/index.ts
- src/components/TaskManagement/TaskDrawer/SupportTeamField/locale/messages.ts
- src/components/TaskManagement/TaskDrawer/SupportTeamField/support-team-popover.tsx
- src/components/TaskManagement/TaskDrawer/SupportTeamField/wrapper.tsx
- src/components/TaskManagement/TaskDrawer/description-section.tsx
- src/components/TaskManagement/TaskDrawer/index.tsx
- src/components/TaskManagement/TaskDrawer/title-section.tsx
- src/components/TaskManagement/hooks/new-task/use-add-task.ts
- src/components/TaskManagement/hooks/new-task/use-delete-task.ts
- src/components/TaskManagement/hooks/new-task/use-get-team-tasks.ts
- src/components/TaskManagement/hooks/new-task/use-update-task.ts
- src/components/TaskManagement/hooks/use-add-task-new.ts
- src/components/TaskManagement/hooks/use-delete-tasks.ts
- src/services/new-task-management/new-task-management.service.ts
- Re-fatorado tipagem do service de tasks para se adaptar á lógica do backend, onde temos 2 formulários diferentes, um para post e put, outro para get.
- Re-feito componente de support team para tasks adaptando a lógica completamente para tasks.
> fix support team field in tasks

- src/components/KeyResult/Single/Sections/Checklist/ActionButtons/create-task-in-kr.tsx
- src/components/KeyResult/Single/Sections/Checklist/checklist.tsx
- src/components/KeyResult/Single/Sections/Checklist/inline-tasklist.tsx
- src/components/Page/MyThings/ActiveCycles/my-tasks/index.tsx
- src/components/Page/MyThings/ActiveCycles/my-tasks/tasks.tsx
- src/components/TaskManagement/hooks/new-task/use-update-task.ts
- src/components/TaskManagement/hooks/use-add-task-new.ts
- user automatically added to kr where a task with him in the team is created.
> my-things finished

- src/components/KeyResult/Single/Sections/Checklist/inline-tasklist.tsx
- Disabled owner change feature for my things tasks.
> disabled owner change feature from my-things

- src/components/KeyResult/Single/Sections/Checklist/hooks/use-update-task.ts
- fix task refetch for card bud-51
> fix task refetch

- src/components/Base/NoticesBanner/index.tsx
- change speed survey link to new nps
> change speed survey link
